# A list of configuration parameters that are specific to the the application user.

env_vars:
  AIRFLOW_HOME: /home/airflow
  USER: marouane-skandaji
  DAGS_FOLDER: /home/airflow/
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW_CTX_DAG_OWNER: marouane-skandaji
  # AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  # AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql://airflow:airflow@postgres:5432/airflow"
  # etc ...

get_latest_repos:
  git_folder: /home/marouane-skandaji/git-personal
  repo_list:
  - scheduler
  - find-your-way
