# This workflow will install Python dependencies, run tests and lint your commit
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci pipeline

on:
  # any push or PR to any branch
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository content
        uses: actions/checkout@v2

      # setup python
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # environment setup
      - name: Install dependencies
        run: python -m pip install --upgrade pip && python -m pip install .[dev]

      # run pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files
        env:
          PRE_COMMIT_HOME: ${{ runner.workspace }}/.cache/pre-commit

      # run tests
      - name: Run tests
        run: make test
